import test from 'node:test';
import assert from 'node:assert/strict';
import {BilliardsSession,BILLIARDS_TABLE as T,BILLIARDS_POCKETS} from '../src/game/BilliardsSession.js';
function table(entries,opponent='beton'){const game=new BilliardsSession({opponent});game.start();for(const b of game.state.balls){b.pocketed=true;b.vx=b.vy=0;}for(const [id,x,y] of entries)Object.assign(game.state.balls.find(b=>b.id===id),{x,y,pocketed:false});return game;}
function settle(game){for(let n=0;n<1200&&game.state.phase==='rolling';n++)game.update(1/60);assert.notEqual(game.state.phase,'rolling','shot must settle');}
function resolve({groups={player:'solids',opponent:'stripes'},turn='player',targets=[1,2],first=1,pocketed=[],rail=true}={}){const game=new BilliardsSession();game.start();Object.assign(game.state,{phase:'rolling',turn,groups,shot:{player:turn,legalTargets:targets,firstContact:first,pocketed,railAfterContact:rail,groupAtStart:groups[turn]}});for(const id of pocketed)game.state.balls.find(b=>b.id===id).pocketed=true;game.finishShot();return game;}

test('rack : 16 billes uniques, 8 centrale, aucun chevauchement, départ confirmé',()=>{const g=new BilliardsSession();assert.equal(g.state.phase,'ready');assert.equal(g.shoot(),false);assert.equal(new Set(g.state.balls.map(b=>b.id)).size,16);assert.equal(g.state.balls.find(b=>b.id===8).y,415);for(const a of g.state.balls)for(const b of g.state.balls)if(a!==b)assert.ok(Math.hypot(a.x-b.x,a.y-b.y)>=24);assert.ok(g.start());assert.equal(g.start(),false);});
test('collision frontale transfère la vitesse et le premier contact',()=>{const g=table([[0,400,415],[1,425,415],[8,900,600]]);g.shoot(0,.5);g.step(1/180);assert.equal(g.state.shot.firstContact,1);assert.ok(g.state.balls.find(b=>b.id===1).vx>400);assert.ok(g.cue().vx<25);});
test('collision oblique dévie les deux billes sans pénétration',()=>{const g=table([[0,400,415],[1,425,426],[8,900,600]]);g.shoot(0,.5);for(let i=0;i<5;i++)g.step(1/180);const b=g.state.balls.find(b=>b.id===1);assert.equal(g.state.shot.firstContact,1);assert.ok(b.vy>0&&g.cue().vy<0);assert.ok(Math.hypot(g.cue().x-b.x,g.cue().y-b.y)>=23.99);});
test('la bande réfléchit une bille et la friction finit par l’arrêter',()=>{const g=table([[0,400,T.y+13],[1,900,550],[8,950,550]]);g.shoot(-Math.PI/2,.5);g.step(1/180);assert.ok(g.cue().vy>0);settle(g);assert.ok(g.state.balls.every(b=>b.vx===0&&b.vy===0));});
for(const [index,p] of BILLIARDS_POCKETS.entries())test(`la poche ${index+1} capture réellement une bille et retire sa vitesse`,()=>{const x=p.x===T.x?p.x+20:p.x===T.x+T.width?p.x-20:p.x,y=p.y===T.y?p.y+20:p.y-20;const g=table([[0,350,415],[1,x,y],[8,900,500]]);g.shoot(0,.12);const b=g.state.balls.find(b=>b.id===1);b.vx=(p.x-x)*8;b.vy=(p.y-y)*8;for(let i=0;i<15&&!b.pocketed;i++)g.step(1/180);assert.ok(b.pocketed);assert.equal(b.vx,0);assert.ok(g.state.shot.pocketed.includes(1));});
test('première poche légale attribue les groupes et conserve la main',()=>{const g=resolve({groups:{player:null,opponent:null},targets:[1,9],first:9,pocketed:[9]});assert.deepEqual(g.state.groups,{player:'stripes',opponent:'solids'});assert.equal(g.state.turn,'player');assert.equal(g.state.phase,'aiming');});
test('empocher seulement le groupe adverse passe la main sans retirer les billes',()=>{const g=resolve({first:1,pocketed:[9]});assert.equal(g.state.turn,'opponent');assert.equal(g.state.lastShot.foul,null);assert.ok(g.state.balls.find(b=>b.id===9).pocketed);});
test('mauvais premier contact, aucune touche et aucune bande donnent blanche en main',()=>{for(const config of [{first:9,pocketed:[1]},{first:null},{first:1,rail:false}]){const g=resolve(config);assert.equal(g.state.phase,'ball-in-hand');assert.equal(g.state.turn,'opponent');assert.ok(g.state.lastShot.foul);}});
test('blanche empochée : aucun groupe attribué, placement libre sans overlap',()=>{const g=resolve({groups:{player:null,opponent:null},targets:[1,9],first:1,pocketed:[1,0]});assert.deepEqual(g.state.groups,{player:null,opponent:null});assert.equal(g.state.phase,'ball-in-hand');const target=g.state.balls.find(b=>b.id===9);assert.equal(g.placeCue(target.x,target.y),false);assert.equal(g.placeCue(T.x,T.y),false);assert.equal(g.placeCue(NaN,500),false);assert.ok(g.placeCue(250,300));assert.ok(g.confirmPlacement());assert.equal(g.state.phase,'aiming');});
test('la 8 gagne uniquement si autorisée au début du coup et sans faute',()=>{const win=resolve({targets:[8],first:8,pocketed:[8]});assert.equal(win.state.winner,'player');assert.equal(win.state.phase,'finished');const early=resolve({targets:[1],first:1,pocketed:[1,8]});assert.equal(early.state.winner,'opponent');const scratch=resolve({targets:[8],first:8,pocketed:[8,0]});assert.equal(scratch.state.winner,'opponent');const foul=resolve({targets:[8],first:9,pocketed:[8]});assert.equal(foul.state.winner,'opponent');});
test('la cible devient 8 seulement après la dernière bille du groupe',()=>{const g=table([[0,350,415],[1,700,300],[8,800,400],[9,900,500]]);g.state.groups={player:'solids',opponent:'stripes'};assert.deepEqual(g.targets().map(b=>b.id),[1]);g.state.balls.find(b=>b.id===1).pocketed=true;assert.deepEqual(g.targets().map(b=>b.id),[8]);});
test('pause : positions, horloges, IA, tirs et placements restent gelés',()=>{const g=new BilliardsSession();g.start();g.shoot(0,.9);g.update(.1);g.pause();const before=JSON.stringify(g.state);for(let i=0;i<100;i++)g.update(.1);assert.equal(JSON.stringify(g.state),before);assert.equal(g.shoot(0,.5),false);g.resume();g.update(.1);assert.notEqual(JSON.stringify(g.state),before);const bot=table([[0,400,415],[1,650,400],[8,900,550]],'kramer');bot.state.turn='opponent';bot.update(.1);bot.pause();const frozen=JSON.stringify(bot.state);for(let i=0;i<30;i++)bot.update(.1);assert.equal(JSON.stringify(bot.state),frozen);bot.resume();for(let i=0;i<11;i++)bot.update(.1);assert.equal(bot.state.phase,'rolling');});
test('l’IA prépare un coup vers une poche, puis la physique empoche la cible',()=>{for(const opponent of ['beton','kramer']){const g=table([[0,640,500],[1,640,300],[8,950,550]],opponent);g.state.turn='opponent';g.state.groups={player:'stripes',opponent:'solids'};const plan=g.planAI();assert.ok(Number.isFinite(plan.angle));assert.ok(plan.power>=.12&&plan.power<=1);g.shoot(plan.angle,plan.power);settle(g);assert.ok(g.state.balls.find(b=>b.id===1).pocketed,opponent);assert.equal(g.state.turn,'opponent');assert.equal(g.state.lastShot.foul,null);}});
test('pas fixe : la casse donne le même résultat à 30 et 60 images/s',()=>{const run=dt=>{const g=new BilliardsSession();g.start();g.shoot(.012,.9);for(let i=0;i<1000&&g.state.phase==='rolling';i++)g.update(dt);return g;};const a=run(1/30),b=run(1/60);assert.equal(a.state.phase,b.state.phase);assert.equal(a.state.turn,b.state.turn);for(const ball of a.state.balls){const other=b.state.balls.find(o=>o.id===ball.id);assert.equal(ball.pocketed,other.pocketed);assert.ok(Math.hypot(ball.x-other.x,ball.y-other.y)<1e-7);}});
test('les commandes invalides et la double résolution ne changent pas le résultat',()=>{const g=resolve({targets:[8],first:8,pocketed:[8]});const before=JSON.stringify(g.state);g.finishShot();assert.equal(g.shoot(0,.5),false);g.update(Infinity);g.update(-1);assert.equal(JSON.stringify(g.state),before);const h=new BilliardsSession();h.start();for(const [a,p] of [[NaN,.5],[0,NaN],[0,0],[0,1.1]])assert.equal(h.shoot(a,p),false);});
test('une partie complète se termine sans bille bloquée ni nombre non fini',()=>{for(const opponent of ['beton','kramer']){const g=new BilliardsSession({opponent});g.start();for(let i=0;i<6000&&g.state.phase!=='finished';i++){if(g.state.turn==='player'){if(g.state.phase==='ball-in-hand'){const p=g.findCuePosition();g.placeCue(p.x,p.y);g.confirmPlacement();}if(g.state.phase==='aiming'){const p=g.planAI();g.shoot(p.angle,p.power);}}g.update(.1);}assert.equal(g.state.phase,'finished',opponent);assert.ok(['player','opponent'].includes(g.state.winner));assert.ok(g.state.shots>5&&g.state.shots<200);assert.ok(g.state.balls.every(b=>[b.x,b.y,b.vx,b.vy].every(Number.isFinite)));}});
