import assert from 'node:assert/strict';
import fs from 'node:fs';
import {chromium,wait,fit,dispatch,joyPoint,buttonPoint,suppressHotReload} from './control-helpers.mjs';
import {CareerProfile,CAREER_STORAGE_KEY} from '../src/game/CareerProfile.js';
const url=process.env.SPARRING_URL??'http://127.0.0.1:5173/';
const browser=await chromium.launch({headless:true});
const report={date:new Date().toISOString(),url,fixture:'Isolated career seeded through the in-game test-profile API; subsequent walks, doors, meals and actions use actual keyboard/CDP touch.',mobileEmulated:true,cases:[],errors:[],failure:null};
let activePage;const contexts=new Set();
function fixture(chapter){const p=new CareerProfile({storage:null});assert.equal(p.applyTestCommand(`test ${chapter==='mexico'?'mexique':'dore'}`).ok,true);if(chapter==='gold')p.setLocation({scene:'hotel-lobby',x:1760,y:420,facing:'down'});return p;}
const saved=p=>p.evaluate(key=>JSON.parse(localStorage.getItem(key)),CAREER_STORAGE_KEY);
const state=p=>p.evaluate(()=>{const w=[window.__mexico,window.__hotel].find(v=>v?.scene.sys.isActive());return w?{place:w.scene.place,...w.world.state,dialog:Boolean(w.ui.dialog)}:null;});
async function ready(p,place){await wait(p,place=>document.querySelector('#stage')?.dataset.scene===place,place,45000);await p.locator('#scene-loading').waitFor({state:'hidden'});await p.waitForTimeout(180);}
async function controls(p,mobile){
  const cdp=mobile?await p.context().newCDPSession(p):null;
  const root=()=>p.evaluate(()=>['gym','rhythm','sparring'].map(id=>`#${id}-ui`).find(s=>{const e=document.querySelector(s);return e&&!e.hidden&&e.getClientRects().length;}));
  const tap=async s=>{if(!mobile)return p.locator(s).click();await dispatch(cdp,'touchStart',[await buttonPoint(p,s)]);await dispatch(cdp,'touchEnd');};
  const hold=async(d,ms)=>{const key={up:'KeyW',down:'KeyS',left:'KeyA',right:'KeyD'}[d];if(mobile)await dispatch(cdp,'touchStart',[await joyPoint(p,await root(),d)]);else await p.keyboard.down(key);await p.waitForTimeout(ms);if(mobile)await dispatch(cdp,'touchEnd');else await p.keyboard.up(key);await p.waitForTimeout(25);};
  const confirm=async()=>mobile?tap(`${await root()} [data-pad-button="a"]`):p.keyboard.press('KeyE');
  const select=async(s)=>{await p.locator(s).waitFor({state:'visible'});if(mobile){await tap(s);return;}for(let n=0;n<28;n++){if(await p.evaluate(s=>document.activeElement?.matches(s),s)){await confirm();return;}await p.keyboard.press('ArrowDown');}throw Error(`Unreachable menu ${s}`);};
  const axis=async(a,value)=>{const initial=await state(p);for(let i=0;i<180;i++){const s=await state(p);if(!s||s.place!==initial.place||s.dialog)return;const d=value-s[a];if(Math.abs(d)<8)return;await hold(a==='x'?d>0?'right':'left':d>0?'down':'up',Math.max(25,Math.min(230,Math.abs(d)/230*760)));}throw Error(`Blocked ${a}=${value}: ${JSON.stringify(await state(p))}`);};
  return{root,tap,hold,axis,confirm,select,pause:async()=>mobile?tap(`${await root()} .console-menu-button`):p.keyboard.press('KeyP'),punch:async(k='jab')=>mobile?tap(`${await root()} [data-pad-button="${k==='jab'?'a':'b'}"]`):p.keyboard.press(k==='jab'?'KeyJ':'KeyK')};
}
async function capture(p,c,mobile,name){const geometry=await fit(p,await c.root(),mobile);assert.ok(geometry.fits&&geometry.noScroll);assert.ok(Math.abs(geometry.ratio-16/9)<.002);assert.equal(geometry.controls.length===0,!mobile);for(const control of geometry.controls)assert.ok(control.fits&&control.outside);await p.screenshot({path:`docs/destinations-${name}-${mobile?'mobile':'desktop'}.png`});report.cases.push({name:`${name}-${mobile?'mobile':'desktop'}`,geometry});console.log(`Destinations: ${name} ${mobile?'mobile':'desktop'}`);}
async function setup(chapter,mobile){const context=await browser.newContext({viewport:mobile?{width:568,height:320}:{width:1440,height:1000},isMobile:mobile,hasTouch:mobile});contexts.add(context);await suppressHotReload(context);await context.addInitScript(({key,value})=>{if(!localStorage.getItem(key))localStorage.setItem(key,value);},{key:CAREER_STORAGE_KEY,value:fixture(chapter).exportText()});const p=await context.newPage();activePage=p;p.setDefaultTimeout(45000);p.on('pageerror',e=>report.errors.push(e.stack??e.message));p.on('console',m=>{if(m.type()==='error')report.errors.push(m.text());});p.on('response',r=>{if(r.status()>=400)report.errors.push(`${r.status()} ${r.url()}`);});const c=await controls(p,mobile);await p.goto(`${url}?scene=${chapter==='mexico'?'mexico-home':'hotel-lobby'}`);return{context,p,c};}
async function mexico(mobile){const {context,p,c}=await setup('mexico',mobile);await ready(p,'mexico-home');const initial=await saved(p);await capture(p,c,mobile,'posada');
  await c.axis('x',825);await c.axis('y',375);await c.confirm();await c.select('[data-gym-action="sleep"]');await wait(p,()=>document.querySelector('#gym-dialog-title')?.textContent.includes('Bon matin'));await c.select('[data-gym-action="close"]');let after=await saved(p);assert.equal(after.daily.day,initial.daily.day+1);assert.equal(after.daily.energy,100);assert.deepEqual(after.stats,initial.stats);assert.deepEqual(after.mexico,initial.mexico);
  await c.axis('y',550);await c.axis('x',640);await c.axis('y',692);await ready(p,'mexico-village');await capture(p,c,mobile,'village');await c.axis('x',1048);await c.axis('y',360);await ready(p,'mexico-gym');await c.axis('y',550);await c.axis('x',430);await c.axis('y',515);await capture(p,c,mobile,'gym');await c.confirm();await c.select('[data-gym-action="activity-pads"]');await ready(p,'pads');await c.select('.rhythm-primary');await wait(p,()=>__hotelActivity.session.state.phase==='running');await c.punch();await p.waitForTimeout(500);await c.punch('cross');await wait(p,()=>__hotelActivity.session.state.stats.hits>=1);assert.equal(await p.evaluate(()=>__hotelActivity.scene.coachId),'octopus');assert.ok(await p.evaluate(()=>__hotelActivity.contacts.every(c=>c.visual.error<.01)));assert.equal((await saved(p)).daily.energy,90);await capture(p,c,mobile,'pads');await c.tap('#rhythm-ui .activity-exit-button');await ready(p,'mexico-gym');
  await c.axis('y',615);await c.axis('x',1040);await c.confirm();await c.select('[data-gym-action="pablo-sparring"]');await ready(p,'sparring');await c.select('#sparring-ui .primary-button');await wait(p,()=>__sparring.session.state.phase==='running');await c.punch();await wait(p,()=>__sparring.session.state.stats.thrown>=1);await capture(p,c,mobile,'pablo');assert.equal((await saved(p)).daily.energy,70);await c.tap('#sparring-ui .activity-exit-button');await ready(p,'mexico-gym');
  await c.axis('x',640);await c.axis('y',690);await ready(p,'mexico-village');await c.axis('y',550);await c.axis('x',1885);await ready(p,'mexico-beach');await capture(p,c,mobile,'promenade');await c.axis('x',1366);await c.axis('y',470);await ready(p,'mexico-arena');await c.axis('y',760);await capture(p,c,mobile,'arena');await c.axis('y',650);await ready(p,'sparring');await c.select('#sparring-ui .primary-button');await wait(p,()=>__sparring.session.state.phase==='running');await c.punch();await wait(p,()=>__sparring.session.state.stats.thrown>=1);await capture(p,c,mobile,'danielo');assert.equal((await saved(p)).daily.energy,70);await c.tap('#sparring-ui .activity-exit-button');await ready(p,'mexico-arena');
  assert.ok(Math.abs((await state(p)).x-960)<5);assert.ok(Math.abs((await state(p)).y-760)<5);if(mobile){await p.setViewportSize({width:390,height:844});await p.locator('#rotate-prompt').waitFor({state:'visible'});assert.equal((await state(p)).paused,true);await p.setViewportSize({width:568,height:320});await c.select('.gym-resume-button');}
  await c.axis('y',1050);await ready(p,'mexico-beach');await c.axis('y',600);await c.axis('x',55);await ready(p,'mexico-village');await c.axis('x',700);await c.axis('y',885);await c.axis('x',390);await c.confirm();await c.select('[data-gym-action="leave-mexico"]');await ready(p,'airport');after=await saved(p);assert.equal(after.mexico.active,null);assert.equal(after.mexico.history.length,1);assert.equal(after.wallet.money,initial.wallet.money);assert.deepEqual(after.stats,initial.stats);
  report.cases.push({name:`mexico-full-trip-${mobile?'mobile':'desktop'}`,sleepOnlyRefills:true,padsHit:true,pabloRealPunch:true,danieloRealPunch:true,paidOnce:true,returnAirport:true,walkingDoors:true});await context.close();contexts.delete(context);
}
async function gold(mobile){const {context,p,c}=await setup('gold',mobile);await ready(p,'hotel-lobby');const initial=await saved(p);assert.equal(initial.tournament.active.tier,'gold');await c.axis('y',450);await c.axis('x',728);await capture(p,c,mobile,'gold-lobby');await c.axis('y',320);await ready(p,'hotel-restaurant');await capture(p,c,mobile,'restaurant');await c.axis('y',550);await c.axis('x',480);await c.axis('y',340);await c.confirm();await c.select('[data-gym-action="bread-baguette"]');await c.select('[data-gym-action="close"]');await c.axis('x',735);await c.confirm();await c.select('[data-gym-action="bread-toast"]');await c.select('[data-gym-action="close"]');await c.axis('x',607);await c.confirm();await c.select('[data-gym-action="bread-herbs"]');assert.match(await p.locator('#gym-dialog-title').textContent(),/Bon appétit/);await capture(p,c,mobile,'bread-served');await c.select('[data-gym-action="close"]');let after=await saved(p);assert.deepEqual(after.daily,initial.daily);assert.deepEqual(after.stats,initial.stats);assert.deepEqual(after.wallet,initial.wallet);
  await c.axis('y',550);await c.axis('x',640);await c.axis('y',672);await ready(p,'hotel-lobby');await c.axis('y',440);await c.axis('x',1495);await c.axis('y',320);await ready(p,'hotel-venue');await capture(p,c,mobile,'gold-venue');await c.axis('y',1380);await c.axis('x',510);await c.confirm();assert.match(await p.locator('#gym-dialog-text').textContent(),/Rafael Ríos/);assert.ok(!/Bellini|Fortin|Gagnon/.test(await p.locator('#gym-dialog-text').textContent()));await capture(p,c,mobile,'gold-board');await c.select('[data-gym-action="close"]');
  report.cases.push({name:`gold-hotel-${mobile?'mobile':'desktop'}`,walkingRestaurant:true,breadToastSpread:true,noStatsOrEnergyChange:true,ownBracket:true});await context.close();contexts.delete(context);
}
try{for(const mobile of [false,true]){if(process.env.DEST_DEVICE&&process.env.DEST_DEVICE!==(mobile?'mobile':'desktop'))continue;for(const part of ['mexico','gold'])if(!process.env.DEST_PART||process.env.DEST_PART===part)await(part==='mexico'?mexico:gold)(mobile);}assert.deepEqual(report.errors,[]);}catch(error){report.failure=error.stack;process.exitCode=1;console.error(error);if(activePage&&!activePage.isClosed())await activePage.screenshot({path:'docs/destinations-browser-failure.png'}).catch(()=>{});}finally{for(const context of contexts)await context.close();await browser.close();fs.writeFileSync(`docs/destinations-${process.env.DEST_PART?process.env.DEST_PART+'-':''}${process.env.DEST_DEVICE?process.env.DEST_DEVICE+'-':''}browser-results.json`,JSON.stringify(report,null,2)+'\n');}console.log(JSON.stringify({cases:report.cases.length,errors:report.errors,failure:report.failure},null,2));
